//
// Generated file, do not edit! Created by opp_msgc 4.3 from selfmsg.msg.
//

#ifndef _SELFMSG_M_H_
#define _SELFMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


namespace csma {

/**
 * Class generated from <tt>selfmsg.msg</tt> by opp_msgc.
 * <pre>
 * message SelfMsg
 * {
 *     int src;
 *     int dest;
 *     int length;
 *     simtime_t backoff_timer;
 *     
 * }
 * </pre>
 */
class SelfMsg : public ::cMessage
{
  protected:
    int src_var;
    int dest_var;
    int length_var;
    simtime_t backoff_timer_var;

  private:
    void copy(const SelfMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SelfMsg&);

  public:
    SelfMsg(const char *name=NULL, int kind=0);
    SelfMsg(const SelfMsg& other);
    virtual ~SelfMsg();
    SelfMsg& operator=(const SelfMsg& other);
    virtual SelfMsg *dup() const {return new SelfMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
    virtual int getLength() const;
    virtual void setLength(int length);
    virtual simtime_t getBackoff_timer() const;
    virtual void setBackoff_timer(simtime_t backoff_timer);
};

inline void doPacking(cCommBuffer *b, SelfMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SelfMsg& obj) {obj.parsimUnpack(b);}

}; // end namespace csma

#endif // _SELFMSG_M_H_
